---


- name: Create the project directory
  file:
    path: "{{ project_url }}"
    state: directory
    mode: '0755'

- name: Copy project files
  copy:
    src: "{{ item }}"
    dest: "{{ project_url }}/"
    directory_mode: yes
  with_items:
    - certbot
    - docker-entrypoint-initdb.d
    - nginx
    - php-fpm
    - postal
    - redis
    - .gitignore

# - name: Clean nginx site configs
#   block:
#     # shell: "rm -rf {{ project_url }}/*.conf"
#     - find:
#         paths: "{{ project_url }}"
#         patterns: "*.conf"
#       register: conf_files
#     - file:
#         path: "{{ item.path }}"
#         state: absent
#       with_items: "{{ conf_files.files }}"
