---
# tasks file for docker-web-stack

- include_tasks: tasks/files.yml

# - name: Pull docker-postal
#   block:
#     - stat:
#         path: "{{ project_url }}/postal"
#       register: postal_repo
#     - git:
#         repo: https://github.com/CatDeployed/docker-postal.git
#         dest: "{{ project_url }}/postal"
#       when: postal_repo.stat.exists != true
#   when: app_install_mailserver

- set_fact:
    nginx_ssl: false

- include_tasks: tasks/templates.yml

- include_tasks: tasks/services.yml

- include_tasks: tasks/additional-user.yml
  when: app_install_database and app_install_mailserver

- include_tasks: tasks/ssl.yml
  when: app_enable_ssl
