---

# - name: Ensure Pip is installed.
  # package: name="{{ 'python3-pip' if python_version == 3 else 'python-pip' }}" state=present

- name: Ensure docker-compose pip module
  become: true
  pip: name=docker-compose

- name: Create and start services
  become: true
  docker_compose:
    project_src: "{{ project_url }}"
    build: yes
  register: output

- debug:
    var: output