---


- name: Ensure docker-compose pip module
  pip: name=docker-compose

- name: Create and start services
  become: true
  docker_compose:
    project_src: "{{ project_url }}"
    build: yes
  register: output

- debug:
    var: output