---


- name: Init letsencrypt
  become: true
  shell:
    chdir: "{{ project_url }}"
    cmd: ./init-letsencrypt.sh
  register: output

- debug:
    msg: "{{ output.stdout_lines }}"

# So that nginx templates inclode ssl certs
- set_fact:
    nginx_ssl: true
    cert_domain: "{% if app_subdomains.0 != '' %}{{ app_subdomains.0 }}.{% endif %}{{ app_domain }}" # takes first subdomain. Must be consistent with line 8 of `init-letsencrypt.sh`

- include_tasks: tasks/templates-nginx.yml

- name: Waiting for nginx
  wait_for:
    host: 0.0.0.0
    port: 80
    # delay: 10

- name: Reload nginx
  become: true
  shell: docker exec {{ app_domain }}-nginx nginx -s reload

