---

- name: Template {{ app_domain }} nginx conf
  template:
    src: nginx_web.conf.j2
    dest: "{{ project_url }}/nginx/sites/{{ app_domain }}.conf"

- name: Template {{ mailserver_hostname }}.{{ app_domain }} nginx conf
  template:
    src: nginx_mail.conf.j2
    dest: "{{ project_url }}/nginx/sites/{{ mailserver_hostname }}.{{ app_domain }}.conf"
  when: app_install_mailserver

- name: Template {{ app_backend }}.{{ app_domain }} nginx conf
  template:
    src: nginx_backend.conf.j2
    dest: "{{ project_url }}/nginx/sites/{{ app_backend }}.{{ app_domain }}.conf"
  when: app_backend != false
