---

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ project_url }}/docker-compose.yml"

- name: Template .env
  template:
    src: .env
    dest: "{{ project_url }}/.env"

- name: Template postal config
  template:
    src: postal.yml
    dest: "{{ project_url }}/postal/postal.yml"
  when: app_install_mailserver

- include_tasks: tasks/templates-nginx.yml

- name: Template init-letsencrypt.sh
  template:
    src: init-letsencrypt.sh
    dest: "{{ project_url }}/init-letsencrypt.sh"
    mode: +x
  when: app_enable_ssl

