---

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ project_url }}/docker-compose.yml"

# - name: Template docker compose env
#   template:
#     src: .env.j2
#     dest: "{{ project_url }}/.env"

- include_tasks: tasks/templates-nginx.yml

- name: Template init-letsencrypt.sh
  template:
    src: init-letsencrypt.sh
    dest: "{{ project_url }}/init-letsencrypt.sh"
    mode: +x
  when: app_enable_ssl

