FROM ruby:2.6-alpine

ENV DOCKERIZE_VERSION v0.6.1


###########################################################################
# App & Dependencies:
###########################################################################

RUN apk --no-cache add nodejs mariadb-client git bash libcap build-base mariadb-dev tzdata mariadb-connector-c openssl \
        && git clone https://github.com/atech/postal.git /opt/postal \
	&& rm -rf /var/lib/apt/lists/* \
	&& gem install bundler \
	&& gem install procodile \
	&& gem install tzinfo-data \
	&& addgroup -S postal \
	&& adduser -S -G postal -h /opt/postal -s /bin/bash postal \
	&& chown -R postal:postal /opt/postal/ \
	&& /opt/postal/bin/postal bundle /opt/postal/vendor/bundle \
	&& apk del git mariadb-dev \
	&& rm -rf /var/cache/apk/*



###########################################################################
# Install jwilder/dockerize:
###########################################################################

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz



###########################################################################
# Adjust permissions:
###########################################################################

RUN setcap 'cap_net_bind_service=+ep' $(which ruby)



WORKDIR /opt/postal



ADD run.sh /run.sh

# Convert DOS/Windows newline (CRLF) to Unix newline (LF)
RUN sed -i "s/\r$/ /g" /run.sh
RUN chmod +x /run.sh



ARG DB_HOST=mariadb
ARG POSTAL_FNAME
ARG POSTAL_LNAME
ARG POSTAL_PASSWORD
ARG POSTAL_EMAIL

ENV DB_HOST $DB_HOST
ENV POSTAL_FNAME $POSTAL_FNAME
ENV POSTAL_LNAME $POSTAL_LNAME
ENV POSTAL_PASSWORD $POSTAL_PASSWORD
ENV POSTAL_EMAIL $POSTAL_EMAIL



# EXPOSE 80 443 25 110 143 465 587 993 995 4190
EXPOSE 5000

VOLUME [ "/var/lib/mysql", "/opt/postal/log" ]

CMD ["/run.sh"]