version: "3.1"

networks:
  frontend:
    driver: {{ app_container_networks_driver }}
  backend:
    driver: {{ app_container_networks_driver }}


volumes:
  postal_app:
    driver: {{ volumes_driver }}
  postal_app_asset:
    driver: {{ volumes_driver }}


services:

### Certbot ################################################
  certbot:
    build:
      context: ./certbot
    image: certbot
    container_name: {{ app_domain }}-certbot
    volumes:
      - {{ data_path_host }}/certs:/certs
      - {{ data_path_host }}/letsencrypt:/etc/letsencrypt
      - {{ log_path }}/letsencrypt:/var/log/letsencrypt
      - {{ data_path_host }}/certbot/www:/var/www/certbot
    restart: {{ app_container_restart_mode }}
    # ports:
    #   - {{ certbot_port }}:0000
    environment:
      # - WEBROOT=/path/to/web_root
      - LOGFILE=/var/log/letsencrypt/certrenewal.log
      - DEBUG={{ certbot_debug }}
      - STAGING={{ certbot_staging }}
      - DOMAINS="{% for subdomain in app_subdomains %}{% if subdomain != '' %}{{ subdomain }}.{% endif %}{{ app_domain }}, {% endfor %}"
      - EMAIL={{ certbot_email }}
      - CONCAT={{ certbot_concat }}
      - HEALTH_CHECK_URL={{ app_domain }}:{{ certbot_health_check_port }}
      - PREFERRED_CHALLENGES={{ certbot_preferred_challenges }}
    networks:
      - frontend

### MariaDB ##############################################
{% if app_install_database or app_install_mailserver %}
  mariadb:
    image: mariadb:10.4
    restart: {{ app_container_restart_mode }}
    container_name: {{ app_domain }}-mariadb
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - {{ data_path_host }}/mariadb:/var/lib/mysql
    ports:
      - {{ database_port }}:3306
    networks:
      backend:
        aliases:
          - {{ database_hostname }}
          - database
          - mysql
    environment:
      - TZ={{ app_timezone }}
      - MYSQL_ROOT_PASSWORD={{ database_root_password }}
      - MYSQL_USER={{ database_user }}
      - MYSQL_PASSWORD={{ database_password }}
      - MYSQL_DATABASE={% if app_install_mailserver %}{{ mailserver_database }}{% else %}{{ database }}{% endif %}
{% endif %}

### NGINX ##############################################
  nginx:
    image: nginx:alpine
    restart: {{ app_container_restart_mode }}
    container_name: {{ app_domain }}-nginx
    volumes:
      - ./nginx/sites/:/etc/nginx/conf.d/:ro
      - {{ log_path }}/nginx/:/var/log/nginx/
      - {{ data_path_host }}/letsencrypt:/etc/letsencrypt
      - {{ data_path_host }}/certbot/www:/var/www/certbot
      - {{ app_code_path_host }}:{{ app_code_path_container }}{{ app_code_container_flag }}
      - postal_app:/opt/postal/app/public:ro
      - postal_app_asset:/opt/postal/app/public/assets:ro
    ports:
      - {{ app_host_http_port }}:80
      - {{ app_host_https_port }}:443
    depends_on: [php-fpm{% if app_install_database or app_install_mailserver %}, phpmyadmin{% endif %}{% if app_install_mailserver %}, postal, roundcube{% endif %}]
    networks:
      - frontend
      - backend

# ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - CHANGE_SOURCE={{ php_fpm_change_source }}
        - PHP_VERSION={{ php_version }}
        - PHALCON_VERSION={{ phalcon_version }}
        - INSTALL_BZ2={{ php_fpm_install_bz2 }}
        - INSTALL_GMP={{ php_fpm_install_gmp }}
        - INSTALL_XDEBUG={{ php_fpm_install_xdebug }}
        - INSTALL_PCOV={{ php_fpm_install_pcov }}
        - INSTALL_PHPDBG={{ php_fpm_install_phpdbg }}
        - INSTALL_BLACKFIRE={{ php_fpm_install_backfire }}
        - INSTALL_SSH2={{ php_fpm_install_ssh2 }}
        - INSTALL_SOAP={{ php_fpm_install_soap }}
        - INSTALL_XSL={{ php_fpm_install_xsl }}
        - INSTALL_SMB={{ php_fpm_install_smb }}
        - INSTALL_IMAP={{ php_fpm_install_imap }}
        - INSTALL_MONGO={{ php_fpm_install_mongo }}
        - INSTALL_AMQP={{ php_fpm_install_amqp }}
        - INSTALL_CASSANDRA={{ php_fpm_install_cassandra }}
        - INSTALL_GEARMAN={{ php_fpm_install_gearman }}
        - INSTALL_MSSQL={{ php_fpm_install_mssql }}
        - INSTALL_BCMATH={{ php_fpm_install_bcmath }}
        - INSTALL_PHPREDIS={{ php_fpm_install_phpredis }}
        - INSTALL_MEMCACHED={{ php_fpm_install_memcached }}
        - INSTALL_OPCACHE={{ php_fpm_install_opcache }}
        - INSTALL_EXIF={{ php_fpm_install_exif }}
        - INSTALL_AEROSPIKE={{ php_fpm_install_aerospike }}
        - INSTALL_OCI8={{ php_fpm_install_oci8 }}
        - INSTALL_MYSQLI={{ php_fpm_install_mysqli }}
        - INSTALL_PGSQL={{ php_fpm_install_pgsql }}
        - INSTALL_PG_CLIENT={{ php_fpm_install_pg_client }}
        - INSTALL_POSTGIS={{ php_fpm_install_postgis }}
        - INSTALL_INTL={{ php_fpm_install_intl }}
        - INSTALL_GHOSTSCRIPT={{ php_fpm_install_ghostscript }}
        - INSTALL_LDAP={{ php_fpm_install_ldap }}
        - INSTALL_PHALCON={{ php_fpm_install_phalcon }}
        - INSTALL_SWOOLE={{ php_fpm_install_swoole }}
        - INSTALL_TAINT={{ php_fpm_install_taint }}
        - INSTALL_IMAGE_OPTIMIZERS={{ php_fpm_install_image_optimizers }}
        - INSTALL_IMAGEMAGICK={{ php_fpm_install_imagemagick }}
        - INSTALL_CALENDAR={{ php_fpm_install_calendar }}
        - INSTALL_FAKETIME={{ php_fpm_install_faketime }}
        - INSTALL_IONCUBE={{ php_fpm_install_ioncube }}
        - INSTALL_APCU={{ php_fpm_install_apcu }}
        - INSTALL_CACHETOOL={{ php_fpm_install_cachetool }}
        - INSTALL_YAML={{ php_fpm_install_yaml }}
        - INSTALL_RDKAFKA={{ php_fpm_install_rdkafka }}
        - INSTALL_GETTEXT={{ php_fpm_install_gettext }}
        - INSTALL_ADDITIONAL_LOCALES={{ php_fpm_install_additional_locales }}
        - INSTALL_MYSQL_CLIENT={{ php_fpm_install_mysql_client }}
        - INSTALL_PING={{ php_fpm_install_ping }}
        - INSTALL_SSHPASS={{ php_fpm_install_sshpass }}
        - INSTALL_MAILPARSE={{ php_fpm_install_mailparse }}
        - INSTALL_PCNTL={{ php_fpm_install_pcntl }}
        - ADDITIONAL_LOCALES={{ php_fpm_additional_locales }}
        - INSTALL_FFMPEG={{ php_fpm_ffmpeg }}
        - INSTALL_WKHTMLTOPDF={{ php_fpm_install_wkhtmltopdf }}
        - INSTALL_XHPROF={{ php_fpm_install_xhprof }}
        - PUID={{ php_fpm_puid }}
        - PGID={{ php_fpm_pgid }}
        - LOCALE={{ php_fpm_default_locale }}
        - http_proxy
        - https_proxy
        - no_proxy
    image: php-fpm:{{ php_version }}
    container_name: {{ app_domain }}-php{{ php_version }}-fpm
    volumes:
      - ./php-fpm/php{{ php_version }}.ini:/usr/local/etc/php/php.ini
      - {{ app_code_path_host }}:{{ app_code_path_container }}{{ app_code_container_flag }}
    ports:
      - {{ php_fpm_port }}:9000
    extra_hosts:
      - dockerhost:{{ docker_host_ip }}
    environment:
      - PHP_IDE_CONFIG={{ php_fpm_ide_config }}
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - FAKETIME={{ php_fpm_faketime }}
    networks:
      - backend

### phpMyAdmin ###########################################
{% if app_install_database or app_install_mailserver %}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: {{ app_domain }}-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: /phpmyadmin
    depends_on:
      - mariadb
    restart: {{ app_container_restart_mode }}
    networks:
      - backend
{% endif %}


### Redis ################################################
  redis:
    build: ./redis
    image: redis
    container_name: {{ app_domain }}-redis
    volumes:
      - {{ data_path_host }}/redis:/data
    ports:
      - {{ redis_port }}:6379
    networks:
      - backend


{% if app_install_mailserver %}

### Mail ################################################
  postal:
    build: ./postal
    image: postal
    container_name: {{ app_domain }}-postal
    environment:
      - WEB_HOST={{ mailserver_hostname }}.{{ app_domain }}
      - MAIL_HOST={{ mailserver_hostname }}.{{ app_domain }}
      - DB_HOST={{ postal_database_host }}
      - DB_USERNAME={{ postal_database_username }}
      - DB_PASSWORD={{ postal_database_password }}
      - DB_DATABASE={{ mailserver_database }}
      - POSTAL_FNAME={{ postal_admin_fname }}
      - POSTAL_LNAME={{ postal_admin_lname }}
      - POSTAL_PASSWORD={{ postal_admin_password }}
      - POSTAL_EMAIL={{ postal_admin_email }}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER={{ rabbitmq_default_user }}
      - RABBITMQ_PASS={{ rabbitmq_default_pass }}
      - RABBITMQ_VHOST={{ rabbitmq_default_vhost }}
      - RAILS_SECRET_KEY={{ postal_secret_key }}
    volumes:
      - {{ log_path }}/postal/:/opt/postal/log
      - postal_app:/opt/postal/app/public
      - postal_app_asset:/opt/postal/app/public/assets
    depends_on:
      - mariadb
      - rabbitmq
    ports:
      - 25:25       # SMTP                - Required
      # - 110:110     # POP3       STARTTLS - Optional - For webmails/desktop clients
      # - 143:143     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - 465:465     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      # - 587:587     # Submission STARTTLS - Optional - For webmails/desktop clients
      # - 993:993     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
      # - 995:995     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      # - 4190:4190   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: {{ app_domain }}-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER={{ rabbitmq_default_user }}
      - RABBITMQ_DEFAULT_PASS={{ rabbitmq_default_pass }}
      - RABBITMQ_DEFAULT_VHOST=/{{ rabbitmq_default_vhost }}
    networks:
      - backend

  roundcube:
    image: roundcube/roundcubemail
    container_name: {{ app_domain }}-webmail
    volumes:
      - {{ data_path_host }}/roundcube/html/:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST={{ mailserver_hostname }}
      - ROUNDCUBEMAIL_SMTP_SERVER=postal
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mariadb
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER={{ database_user }}
      - ROUNDCUBEMAIL_DB_PASSWORD={{ database_root_password }}
      - ROUNDCUBEMAIL_DB_NAME={{ mailserver_database }}
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE={{ roundcube_upload_max_filesize }}
      - ROUNDCUBEMAIL_PLUGINS={{ roundcube_plugins }}
    depends_on:
      - postal
    restart: {{ app_container_restart_mode }}
    networks:
      - backend

{% endif %}
